/** Compiler bodies protected from accidental executable changes. */
export const PROTECTED_COMPILER_BODIES = Object.freeze([
	Object.freeze({ name: 'compileGuard', hash: '8956106c2a5b310e' }),
	Object.freeze({ name: 'compileParser', hash: '38cb8a315ec4664e' }),
	Object.freeze({ name: 'compileReporter', hash: '348331882c6002bf' }),
])

/** Transitive project-owned executable closure behind every compiled-artifact entry. */
export const PROTECTED_COMPILER_CLOSURE = Object.freeze({
	names: Object.freeze([
		'arrayOf',
		'attempt',
		'boundsOf',
		'cloneSchema',
		'cloneShape',
		'compileAuditor',
		'compileGenerator',
		'compileGuard',
		'compileParser',
		'compileReporter',
		'compileSchema',
		'createContract',
		'drawRandom',
		'enumerableKeys',
		'holds',
		'intersectionOf',
		'isArray',
		'isBigInt',
		'isBoolean',
		'isContractError',
		'isFiniteNumber',
		'isFunction',
		'isInstance',
		'isJSONValue',
		'isNumber',
		'isObject',
		'isRecord',
		'isRegExp',
		'isString',
		'isSymbol',
		'literalOf',
		'matchOf',
		'matchesJSONValue',
		'nullableOf',
		'orOf',
		'ownShape',
		'parseBoolean',
		'parseNumber',
		'parseRecord',
		'parseString',
		'preview',
		'readValue',
		'shapeToKind',
		'stringOf',
		'unionOf',
		'validateShape',
		'validateShapeDepth',
		'whereOf',
	]),
	hash: '086a91d430cfd79a',
})
